# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(481, 322)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 480, 320))
        self.label_6.setStyleSheet("image: url(:/newPrefix/main_menu.png);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 110, 51, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 160, 51, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setGeometry(QtCore.QRect(70, 100, 391, 201))
        self.stackedWidget.setStyleSheet("background:transparent")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_mission = QtWidgets.QWidget()
        self.page_mission.setObjectName("page_mission")
        self.checkBox = QtWidgets.QCheckBox(self.page_mission)
        self.checkBox.setEnabled(True)
        self.checkBox.setGeometry(QtCore.QRect(20, 20, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox.setFont(font)
        self.checkBox.setStatusTip("")
        self.checkBox.setCheckable(False)
        self.checkBox.setObjectName("checkBox")
        self.stackedWidget.addWidget(self.page_mission)
        self.page_gsm = QtWidgets.QWidget()
        self.page_gsm.setObjectName("page_gsm")
        self.stackedWidget.addWidget(self.page_gsm)
        self.page_dcc = QtWidgets.QWidget()
        self.page_dcc.setObjectName("page_dcc")
        self.stackedWidget.addWidget(self.page_dcc)
        self.page_cmc = QtWidgets.QWidget()
        self.page_cmc.setObjectName("page_cmc")
        self.stackedWidget.addWidget(self.page_cmc)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 210, 51, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 260, 51, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_3.setText(_translate("MainWindow", "MCC"))
        self.pushButton_4.setText(_translate("MainWindow", "GSM"))
        self.checkBox.setText(_translate("MainWindow", "Control Center Connection"))
        self.pushButton_5.setText(_translate("MainWindow", "DCC"))
        self.pushButton_6.setText(_translate("MainWindow", "CMC"))
import source_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
